/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suraj
 */
public class BooksCart extends javax.swing.JFrame {

    /**
     * Creates new form BooksCart
     */
    public BooksCart() {
        initComponents();
        cartTable.getTableHeader().setFont(new Font("Recoleta",Font.BOLD,12));
        cartTable.getTableHeader().setOpaque(false);
        cartTable.getTableHeader().setBackground(new Color(9,25,69));
        cartTable.getTableHeader().setForeground(new Color(255,255,255));
        cartTable.setRowHeight(25);
        Show_Data();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bcontacttext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payidtext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totaltext = new javax.swing.JTextField();
        dropdown = new javax.swing.JComboBox<>();
        payementbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        bcontacttext1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(64, 205, 232));

        cartTable.setBackground(new java.awt.Color(255, 185, 45));
        cartTable.setForeground(new java.awt.Color(37, 38, 45));
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Quantity", "Price"
            }
        ));
        cartTable.setRowHeight(25);
        cartTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        cartTable.setSelectionForeground(new java.awt.Color(37, 38, 45));
        jScrollPane1.setViewportView(cartTable);

        jLabel1.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buyer's Name");

        bcontacttext.setFont(new java.awt.Font("Product Sans", 1, 12)); // NOI18N
        bcontacttext.setForeground(new java.awt.Color(37, 38, 45));

        jLabel3.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Mode");

        jLabel2.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buyer's Contact");

        jLabel4.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(9, 25, 69));
        jLabel4.setText("Payment ID");

        payidtext.setFont(new java.awt.Font("Product Sans", 1, 12)); // NOI18N
        payidtext.setForeground(new java.awt.Color(37, 38, 45));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payidtext, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(payidtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Recoleta Bold", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 25, 69));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total Amount");

        totaltext.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        totaltext.setForeground(new java.awt.Color(37, 38, 45));
        totaltext.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totaltext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        totaltext.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        totaltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltextActionPerformed(evt);
            }
        });

        dropdown.setFont(new java.awt.Font("Product Sans", 1, 14)); // NOI18N
        dropdown.setForeground(new java.awt.Color(51, 51, 51));
        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UPI", "Card", "Net Banking" }));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        payementbtn.setFont(new java.awt.Font("Recoleta Bold", 0, 15)); // NOI18N
        payementbtn.setForeground(new java.awt.Color(9, 25, 69));
        payementbtn.setText("Make Payment");
        payementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementbtnActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(37, 38, 45));
        jLabel7.setFont(new java.awt.Font("Recoleta Bold", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(9, 25, 69));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PAYMENT DASHBOARD");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        closebtn.setBackground(new java.awt.Color(64, 205, 232));
        closebtn.setFont(new java.awt.Font("Recoleta Bold", 0, 15)); // NOI18N
        closebtn.setForeground(new java.awt.Color(204, 0, 51));
        closebtn.setText("Close");
        closebtn.setBorder(null);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });

        bcontacttext1.setFont(new java.awt.Font("Product Sans", 1, 12)); // NOI18N
        bcontacttext1.setForeground(new java.awt.Color(37, 38, 45));
        bcontacttext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcontacttext1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bcontacttext)
                                            .addComponent(dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bcontacttext1))))
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(payementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(closebtn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(55, 55, 55))
                            .addComponent(totaltext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(bcontacttext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(bcontacttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(payementbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(closebtn)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totaltext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public ArrayList<BookModel> getBooks()
    {
        ArrayList<BookModel> booksList = new ArrayList<BookModel>();
        Connection con = ConnectionManager.getConnection();
        String sql = "SELECT * FROM cart";

        Statement st;
        ResultSet rs;
        
        try{
          
            st = con.createStatement();
            rs = st.executeQuery(sql);
            BookModel bookmodel;
            
            while(rs.next())
            {
                bookmodel = new BookModel(rs.getString("B_ID"),rs.getString("B_Name"),rs.getInt("B_Quantity"),rs.getInt("B_Price"),rs.getString("B_Date"));
                booksList.add(bookmodel);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(this,e.toString());
        }
        return booksList;
    }
    public void Show_Data()
    {
        ArrayList<BookModel> list = getBooks();
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        int payment=0;
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++)
        {
            int total=0;
            row[0]=list.get(i).getID();
            row[1]=list.get(i).getname();
            row[2]=list.get(i).getquantity();
            
            payment=payment+list.get(i).getprice();
            row[3]=list.get(i).getprice();
            model.addRow(row);
        }
        totaltext.setText(String.valueOf(payment));
       
    }
    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownActionPerformed

    private void payementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementbtnActionPerformed
            try{
                Connection con = ConnectionManager.getConnection();
                String sql = "INSERT INTO sales (B_ID,B_Name,B_Quantity,B_Price,B_Date) SELECT B_ID,B_Name,B_Quantity,B_Price,B_Date FROM cart";
                String sql2= "DELETE FROM cart";
                
                PreparedStatement pst = con.prepareStatement(sql);
                PreparedStatement pst2 = con.prepareStatement(sql2);
                
                
                
                int rs = pst.executeUpdate();
                int rs2 = pst2.executeUpdate();
                
                
                if(rs>0  && rs2>0)
                {
                    JOptionPane.showMessageDialog(this,"Payment Successful");
                    DashboardPage_Buyer d = new DashboardPage_Buyer();
                    this.hide();
                    d.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Unable to Make Payement");
                }
               }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(this,e.toString());
            }
    }//GEN-LAST:event_payementbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        DashboardPage_Buyer d = new DashboardPage_Buyer();
        this.hide();
        d.setVisible(true);
    }//GEN-LAST:event_closebtnActionPerformed

    private void totaltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltextActionPerformed

    private void bcontacttext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcontacttext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcontacttext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bcontacttext;
    private javax.swing.JTextField bcontacttext1;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton closebtn;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payementbtn;
    private javax.swing.JTextField payidtext;
    private javax.swing.JTextField totaltext;
    // End of variables declaration//GEN-END:variables
}
