/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;


/**
 *
 * @author suraj
 */
public class RequestBook extends javax.swing.JFrame {

    /**
     * Creates new form RequestBook
     */
    public RequestBook() {
        initComponents();
        cartbtn.setVisible(false);
        gocartbtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        catetext1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        catetext = new javax.swing.JTextField();
        quantitytext = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        cartbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pricetext = new javax.swing.JTextField();
        gocartbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        authortext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        catetext1.setBackground(new java.awt.Color(0, 102, 102));
        catetext1.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookshop/imagesdir/br3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 606, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 38, 45));
        jLabel1.setText("Book Name");

        jLabel2.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 38, 45));
        jLabel2.setText("Book Category");

        jLabel3.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 38, 45));
        jLabel3.setText("Quantity Required");

        nametext.setBackground(new java.awt.Color(64, 205, 232));
        nametext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        nametext.setForeground(new java.awt.Color(255, 255, 255));
        nametext.setCaretColor(new java.awt.Color(255, 255, 255));

        catetext.setBackground(new java.awt.Color(64, 205, 232));
        catetext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        catetext.setForeground(new java.awt.Color(255, 255, 255));
        catetext.setCaretColor(new java.awt.Color(255, 255, 255));

        quantitytext.setBackground(new java.awt.Color(64, 205, 232));
        quantitytext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        quantitytext.setForeground(new java.awt.Color(255, 255, 255));
        quantitytext.setCaretColor(new java.awt.Color(255, 255, 255));
        quantitytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytextActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(9, 25, 69));
        searchbtn.setFont(new java.awt.Font("Recoleta Bold", 0, 15)); // NOI18N
        searchbtn.setForeground(new java.awt.Color(255, 255, 255));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        cartbtn.setBackground(new java.awt.Color(9, 25, 69));
        cartbtn.setFont(new java.awt.Font("Recoleta Bold", 0, 15)); // NOI18N
        cartbtn.setForeground(new java.awt.Color(255, 255, 255));
        cartbtn.setText("Add to Cart");
        cartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(37, 38, 45));
        jLabel4.setText("Price");

        pricetext.setBackground(new java.awt.Color(64, 205, 232));
        pricetext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        pricetext.setForeground(new java.awt.Color(255, 255, 255));
        pricetext.setCaretColor(new java.awt.Color(255, 255, 255));

        gocartbtn.setFont(new java.awt.Font("Recoleta Bold", 0, 15)); // NOI18N
        gocartbtn.setForeground(new java.awt.Color(9, 25, 69));
        gocartbtn.setText("Go To Cart");
        gocartbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gocartbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(37, 38, 45));
        jLabel5.setText("Book ID");

        idtext.setBackground(new java.awt.Color(64, 205, 232));
        idtext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        idtext.setForeground(new java.awt.Color(255, 255, 255));
        idtext.setCaretColor(new java.awt.Color(255, 255, 255));
        idtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Recoleta Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(37, 38, 45));
        jLabel6.setText("Author Name");

        authortext.setBackground(new java.awt.Color(64, 205, 232));
        authortext.setFont(new java.awt.Font("Product Sans", 1, 16)); // NOI18N
        authortext.setForeground(new java.awt.Color(255, 255, 255));
        authortext.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel8.setBackground(new java.awt.Color(37, 38, 45));
        jLabel8.setFont(new java.awt.Font("Recoleta Bold", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(9, 25, 69));
        jLabel8.setText("    REQUEST  FOR  BOOK  ");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(9, 25, 69)));

        backbtn.setFont(new java.awt.Font("Recoleta Bold", 0, 16)); // NOI18N
        backbtn.setForeground(new java.awt.Color(204, 0, 51));
        backbtn.setText("Back");
        backbtn.setBorder(null);
        backbtn.setFocusable(false);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nametext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantitytext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(catetext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(133, 133, 133)
                                        .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pricetext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authortext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gocartbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nametext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(catetext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantitytext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idtext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(authortext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(gocartbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pricetext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        
        try
        {
            Connection con = ConnectionManager.getConnection();
            String sql = "SELECT * FROM stock where book_name=? AND category=? AND quantity>=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,nametext.getText());
            pst.setString(2,catetext.getText());
            pst.setString(3,quantitytext.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this,"Book Available ");
                idtext.setText(rs.getString("book_id"));
                authortext.setText(rs.getString("author"));
                pricetext.setText(rs.getString("price"));
                cartbtn.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Book NOT Available ");
                nametext.setText("");
                catetext.setText("");
                quantitytext.setText("");
            }
            
        }
        catch(SQLException e)
        {
                JOptionPane.showMessageDialog(this,e.toString());
        }
        
    }//GEN-LAST:event_searchbtnActionPerformed

    private void cartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartbtnActionPerformed
            
        try{
                Connection con = ConnectionManager.getConnection();
                String sql = "INSERT INTO cart VALUES(?,?,?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
                LocalDateTime now = LocalDateTime.now();  
                String buy_date = dtf.format(now);
                
                pst.setString(1,idtext.getText());
                pst.setString(2,nametext.getText());
                pst.setString(3,quantitytext.getText());
                int total = (Integer.parseInt(quantitytext.getText()))*(Integer.parseInt(pricetext.getText()));
                System.out.println(total);
                pst.setString(4,String.valueOf(total));
                pst.setString(5,buy_date);
                
                int rs = pst.executeUpdate();
                if(rs>0)
                {
                    JOptionPane.showMessageDialog(this,"Added to cart");
                    gocartbtn.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Can't Add to the Cart");
                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this,e.toString());
            }
    }//GEN-LAST:event_cartbtnActionPerformed

    private void gocartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gocartbtnActionPerformed
            BooksCart d = new BooksCart();
                   this.hide();
                   d.setVisible(true);
    }//GEN-LAST:event_gocartbtnActionPerformed

    private void idtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtextActionPerformed

    private void quantitytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytextActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        DashboardPage_Buyer d = new DashboardPage_Buyer();
        this.hide();
        d.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authortext;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton cartbtn;
    private javax.swing.JTextField catetext;
    private javax.swing.JTextField catetext1;
    private javax.swing.JButton gocartbtn;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField pricetext;
    private javax.swing.JTextField quantitytext;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
